import {Router} from 'express';
import JogadorController from  './app/controllers/JogadorController';
import EnderecoController from './app/controllers/EnderecoController';
import LocalController from './app/controllers/LocalController';
import MapaController from './app/controllers/MapaController';
const router = Router();

//criando  rotas para /jogadores.
router.post('/jogadores', JogadorController.store);//define uma rota vai método post para chamar o método store da classe JogadorController
router.get('/jogadores', JogadorController.list);//define uma rota ...
router.put('/jogadores', JogadorController.update);//define uma rota ...
router.delete('/jogadores', JogadorController.delete);//define uma rota ...


//criando  rotas para /enderecos.
router.post('/enderecos', EnderecoController.store);//define uma rota vai método post para chamar o método store da classe EnderecoController
router.get('/enderecos', EnderecoController.list);//define uma rota ...
router.delete('/enderecos', EnderecoController.delete);//define uma rota ...


router.post('/mapas', MapaController.store);//define uma rota vai método post para chamar o método store da classe JogadorController
router.get('/mapas', MapaController.list);//define uma rota ...
router.put('/mapas', MapaController.update);//define uma rota ...
router.delete('/mapas', MapaController.delete);//define uma rota ...


router.post('/locais', LocalController.store);//define uma rota vai método post para chamar o método store da classe JogadorController
router.get('/locais', LocalController.list);//define uma rota ...
router.put('/locais', LocalController.update);//define uma rota ...
router.delete('/locais', LocalController.delete);//define uma rota ...
export default router;

